version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: |
            python3 -m pip install pipenv
            pipenv install --dev
            pipenv run pip install -e .
            pipenv install codecov
      - run:
          name: Run tests
          command: |
            pipenv run make test-strict
            pipenv run make coverage
            pipenv run codecov
      - store_artifacts:
          path: .coverage.html/
